import os
import yaml

from typing import Dict

from tree.branch.source.source import Source
from tree.branch.branch import Branch


def _load_files(values: Dict) -> Dict:

    """ Loads a list of sources from a dict.

    Expects a dict. encoded as seen in `tree.branch.save`, for example:

    ``` yaml
    sources:
      some_file.hpp:
        hash: 1914a3297b981bb8
        includes:
        - some_other_file.hpp
    ```

    Arguments
    ---------
    values: Dict
        dict. containing file(s) information, as described above

    Returns
    -------
    sources: Dict
        the sources created, encoded as a dict. of name:Source pairs
    """

    # Create a source object for each entry in the values dict.
    result = {}
    for name, file in values.items():
        source = Source()
        source.name = name
        source.hash = file['hash']
        source.includes = file['includes']

        result[name] = source

    return result


def load(path: str, depth: int) -> Branch:

    """ Loads a `.branch` file, as generated by `tree.branch.save`

    Arguments
    ---------
    path: str
        the absolute path of the file to load
    depth: int
        the depth within the cached source tree

    Returns
    -------
    branch: Branch
        the branch generated
    """

    # Open the branch file specified
    branch_file_name = os.path.join(path, '.branch')
    branch_file = open(branch_file_name, 'r')

    # Load its values (yaml encoded)
    values = yaml.safe_load(branch_file)

    # Create a new branch
    branch = Branch()
    branch.path = values['path']
    branch.name = values['name']
    branch.depth = depth

    # Load sources and headers
    branch.sources = _load_files(values['sources'])
    branch.headers = _load_files(values['headers'])

    # Load branches
    for name, hash in values['branches'].items():
        absolute_path = os.path.join(path, name)
        branch_ = load(absolute_path, depth + 1)

        branch_.hash = hash
        branch.branches[name] = branch_

    branch_file.close()
    return branch
